name: Trigger Repo B CI

on:
  push:
    branches:
      - main   # ðŸ‘ˆ branch you care about

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_B_PAT }}" \
          https://api.github.com/repos/YousseffHassaan/Repo-B/dispatches  \
          -d '{"event_type":"run-tests"}'
